version: '3'


volumes:
  postgres_volume:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ps-app
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - pg_statuses

  pg_statuses:
    image: postgres:14-alpine3.17
    container_name: ps-psql
    ports:
      - "${PG_PORT}:5432"
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  
  migrator_pg:
    container_name: ps-psqlMigrator
    build:
      context: .
      dockerfile: migrations.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg_statuses